### ISSUE TITLE
Need for other libraries

### ISSUE THREAD

**Issue by matthieusorel** [metwork-framework/mfextaddon_scientific#11]
Hi all,

In a future versions, other libraries would be great:
- palettable (colormaps including cmocean, cubehelix, etc.);
- seaborn (statistics and dataviz);
- epygram (from CNRM);

Thanks !
Matthieu

**Comment by thefab** [comment]
- `palettable` (accepted in #14)
- `seaborn` (accepted in #15)
- `epygram` @matthieusorel is it an opensource component ? I don't think so

**Comment by matthieusorel** [comment]
You're right, not opensource... Forget about it.

**Comment by thefab** [comment]
I close this issue. The work continue in #14 and #15
