### ISSUE TITLE
protobuf package

### ISSUE THREAD

**Issue by PIfred** [metwork-framework/mfextaddon_scientific#118]
Hello,
Some nowcasting data (objects) are coded in a protocolbuffer format. 
Python coding and decoding needs  protobuf package (google.protobuf). Current processing make a wide use of extend routine, needing at least 3.4.0 release. Any newer release will cover the needs.
Availability of protobuf package in mfext would allow to update existing operational processings
Many thanks
Frederic

**Comment by thebaptiste** [comment]
Do you have an example of the way you use or intend to use protobuf ? It seems that there are two ways of doing so : 
- direct use of the python module
- use of the "proto Compiler" to build python code from a "proto" file : see documentation [here](https://developers.google.com/protocol-buffers/docs/pythontutorial)

This second way seems to be the recommended one but it needs the "proto Compiler" and the "python C++ implementation" to be installed.

**Comment by PIfred** [comment]
I have already compiled a proto file phenomenes.proto using protobuf-3.11.3 compiler and build a python module named phenomenes_pb2.py
This module has then to be imported in the main python source
The objective of the main source is to read a XML file and to encode it  into protocolbuffer format

Is there a risk of non compatibility between the compiled module and the protobuf package to be installed in mfext ?

**Comment by thebaptiste** [comment]
I don't think so, but give me access to your phenomenes.proto and phenomenes_pb2.py files, I will use them for tests.
Is phenomenes.proto in proto2 or proto3 language ?

**Comment by PIfred** [comment]
this is proto2 (so compiled to *_pb2.py)
I attach the main python program, the proto file and the compiled module
Tell me if you want an example of XML file to be converted
[PROD.zip](https://github.com/metwork-framework/mfextaddon_scientific/files/4884636/PROD.zip)

**Comment by thebaptiste** [comment]
The new releases of Metwork are now built under centos8. This OS provide protobuf 3.5.0, which I understand is sufficient for your need.
So, unless this a problem for you, we will remove protobuf from Metwork >= 2.0
