### ISSUE TITLE
plt.show() does not... show

### ISSUE THREAD

**Issue by matthieusorel** [metwork-framework/mfextaddon_scientific#12]
Hi all,

plt.show() does not show.
No errors reported but no figure displayed. Nothing happens.

Matthieu.

**Comment by thebaptiste** [comment]
matplotlib has a backend system (https://matplotlib.org/faq/usage_faq.html#what-is-a-backend)
The "show" function open a window, so it needs a "graphical user interface" backend. For the time being there are no "graphical user interface" on the Metwork build machine with its minimized OS. So no backend is available in matplotlib. We will add TclTk libraries to make available the tkinter module in python and so the TkAgg backend in matplotlib.

**Comment by thefab** [comment]
just released the fix:
https://medium.com/metwork-framework/0-5-and-0-6-minor-updates-e049f26edf0d
