### ISSUE TITLE
eccodes-python : new python 3 interface for eccodes

### ISSUE THREAD

**Issue by matthieusorel** [metwork-framework/mfextaddon_scientific#24]
Hi,

ECMWF just released a new python 3 interface to decode/encode GRIB and BUFR: eccodes-python
https://pypi.org/project/eccodes-python/

Perhaps, this module is more suitable for python 3 users (eccodes has know issues in python 3).

Matthieu.

**Comment by thefab** [comment]
great!

**Comment by thefab** [comment]
let's try to add it for upcoming metwork 0.8 release
