### ISSUE TITLE
Installation of python packages in the next version of metwork

### ISSUE THREAD

**Issue by GabArnould** [metwork-framework/mfextaddon_scientific#448]
Hi,

Would it be possible to install the following packages in the future version ?
* plotly (package to create beautiful and dynamic graphics)
* rtree (geopandas usefull dependancy)
* pyogrio  (geopandas usefull dependancy)
* folium (to generate dynamic graphics with geopandas)
* 
Thank you for your attention.

**Comment by thebaptiste** [comment]
All this packages are now available in Metwork master branch.
You can test and give feedback on this branch.
The date of the next release of Metwork is not yet decided but it won't be before several months, June 2023 at the earliest, may be later...

**Comment by thebaptiste** [comment]
Done by #450
