### ISSUE TITLE
Leaflet and folium

### ISSUE THREAD

**Issue by matthieusorel** [metwork-framework/mfextaddon_scientific#466]
Hello,

Would be great to have folium and leaflet in the new version of MetWork.
https://www.earthdatascience.org/tutorials/introduction-to-leaflet-animated-maps/

Thanks !
Matthieu

**Comment by thebaptiste** [comment]
Hello
folium is already available in the master branch of Metwork.
I will add leaflet soon.
Both should be available in next Metwork release (2.2)

**Comment by thebaptiste** [comment]
Leaflet is kind of included in folium. I was able to reproduce the map given in your link with Metwork master branch without adding any package.
So you can try to play with it. Feel free to report any difficulty or improvement suggestion.

**Comment by matthieusorel** [comment]
Thanks a lot ! Looking forward to testing it when it will be available on our DEV servers @MF ! 😉
