### ISSUE TITLE
New librairies: pytroll 

### ISSUE THREAD

**Issue by matthieusorel** [metwork-framework/mfextaddon_scientific#59]
Hi,

Could you install the pytroll library ? It contains several packages which are very useful to process satellite data:
https://pytroll.readthedocs.io/en/latest/index.html
Each package (pyresample, mipp, mpop, python-bufr, pycoast, etc.) may need to be installed in a different way. More info here: https://pytroll.readthedocs.io/en/latest/index.html

Thanks a lot,
Matthieu.

**Comment by thebaptiste** [comment]
There are "only" 48 packages available on pytroll (see https://github.com/pytroll ). We won't provide 48 new packages in Metwork "just in case someone may need one of them someday".
So please do a more specific request for packages you have tried and you really need (mpop, for example, is deprecated).
May be satpy would be an interesting one...

**Comment by matthieusorel** [comment]
48 ??? Oups !
Here's a selection:
satpy, pyresample, pyorbital, pycoast, pydecorate.

Thanks !
Matthieu.

**Comment by thebaptiste** [comment]
Done
